### ISSUE TITLE
in grid setup with 2 nodes , test cases are run twice

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-demos#22]
@YamStranger  I am trying to use this project to reproduce other issue ( docker + VM ) 

But strangely with command 

mvn clean verify -Dwebdriver.remote.url=http://192.168.99.100:4444/wd/hub -Dwebdriver.remote.driver=chrome -Dwebdriver.remote.os=LINUX

I see all the 7 test cases being run 2 times instead of just one.

First run test cases are distributed to both nodes

Second run , test cases just run on single node. 

I spent an hours and not able to find the root cause , can you please help with this ?

**Comment by vikramvi** [comment]
@YamStranger https://github.com/serenity-bdd/serenity-demos/blob/master/junit-webtests/pom.xml 

wrt this pom.xml , can you please clarify changes I need to do to run test cases on single browser on single machine and  running single browser on each of the nodes on grid setup.

Once I'm done with this , I can use the example to reproduce issue https://github.com/serenity-bdd/serenity-core/issues/353 and share code with you

Thanks in advance

**Comment by vikramvi** [comment]
solved this issue

https://github.com/vikramvi/junit-webtests-parallel-grid-docker-jenkins-debug/blob/master/junit-webtests/pom.xml

maven-failsafe-plugin has bug with parallel execution , so need to use skip flag not to run integration-tests once they are run by maven-surefire-plugin.

**Comment by YamStranger** [comment]
It's good news, thanks
