### ISSUE TITLE
Serenity-Cucumber  jira configuration

### ISSUE THREAD

**Issue by heerqa** [serenity-bdd/serenity-demos#25]
As in the example http://thucydides.info/docs/serenity-staging/#_integrating_with_jira
I am using @issue:<jira task#>
But I am not able to see the comments my jira task comment section.
I am able to see the list of all Jira EPIC, REQUIREMENTS, TASK etc in serenity report.

Having Acceptance Criteria files in Jira is mandatory to link the tests result with jira task?

**Comment by YamStranger** [comment]
Hello @heerqa, thanks for this question, 
moved to serenity-bdd/serenity-jira/issues/38. 
Please follow answers. 
Thanks!
