### ISSUE TITLE
Post run inputs and observations

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-demos#4]
Hi John,

Please find below inputs

1. README report path should be ../target/site/serenity
2. Need to mention that GhostDriver needs to be setup on machine these tests are run.
3. Basic info about PhantomJs ( http://elementalselenium.com/tips/46-headless-ghostdriver )
4. How to start , stop PhantomJs externally or taken care in script itself ?

Thanks & Regards,
Vikram

**Comment by wakaleo** [comment]
Hi Vikram,
Thanks for your comments. When you use PhantomJS with WebDriver, you don't need to start the phantomjs server yourself, or even configure the build script to do so - WebDriver will automatically start up the server for you before the tests start. All you need to do is to download the phantomjs binary and make sure it is on the path.
